// apps/vue-app/src/remotes/About.vue
<script setup>
import { ref, onMounted, onBeforeUnmount } from "vue";

const appPromise = serviceLocator.resolve("vue-component");
const about = ref();
let isMounting = false;
onMounted(async () => {
  isMounting = true;
  const app = await appPromise;

  if (isMounting) {
    app.mount({
      containerSelectors: about.value,
    });
  }
});
onBeforeUnmount(() => {
  isMounting = false;
});
</script>

<template>
  <div ref="about"></div>
</template>

// apps/react-app/src/remotes/About.js
import React, { useEffect } from "react";

const About = () => {
  useEffect(() => {
    let app = null;
    const containerSelectors = "#about";
    (async () => {
      app = await serviceLocator.resolve("vue-component");

      app.mount({
        containerSelectors,
      });
    })();

    return () => {
      app?.unmount({
        containerSelectors,
      });
      app = null;
    };
  }, []);

  return <div id="about"></div>;
};

export default About;
