// apps/about-vue/src/App.g.vue
<script setup>
import { ref, defineProps, onMounted, onBeforeUnmount } from "vue";
import useObservableRootProps from "./use-observable-root-props.g.js";

const rootProps = defineProps({
  title: String,
});
const observableRootProps = useObservableRootProps(rootProps);

const appPromise = window.serviceLocator.resolve("about-uni");
const container = ref();
let isMounting = false;
onMounted(async () => {
  isMounting = true;

  const app = await appPromise;

  if (isMounting) {
    app.mount({
      containerSelectors: container.value,
      observableRootProps,
    });
  }
});
onBeforeUnmount(() => {
  isMounting = false;
});
</script>

<template>
  <div ref="container"></div>
</template>

// apps/about-react/src/App.g.js
import React from "react";
import useObservableRootProps from "./use-observable-root-props.g.js";

const About = (rootProps) => {
  const observableRootProps = useObservableRootProps(rootProps);

  const containerSelectors = "#about";

  React.useEffect(() => {
    let isMounting = true;
    let app = null;

    (async () => {
      app = await window.serviceLocator.resolve("about-uni");

      if (isMounting === false) return;

      app.mount({
        containerSelectors,
        observableRootProps,
      });
    })();

    return () => {
      isMounting = false;

      app?.unmount({
        containerSelectors,
      });
    };
  }, [app]);

  return <div id="about"></div>;
};

export default About;
