// apps/components-vue-3/src/AboutComponent.vue
<script>
import { defineComponent, ref } from "vue";

export default defineComponent({
  props: {
    title: {
      type: String,
      default: "About",
    },
  },
  setup() {
    const count = ref(0);
    const increment = () => count.value++;

    return {
      count,
      increment,
    };
  },
});
</script>

<template>
  <div
    :style="{
      margin: '10px',
      padding: '10px',
      textAlign: 'center',
      backgroundColor: 'green',
      color: 'white',
    }"
  >
    <h1>Props: {{ title }}</h1>
    <button @click="increment">{{ count }}</button>
  </div>
</template>

// apps/react-app/src/views/About.js
import React from "react";
import { useLocation } from "react-router-dom";

export default () => {
  const location = useLocation();

  return (
    <div
      style={{
        margin: "10px",
        padding: "10px",
        textAlign: "center",
        backgroundColor: "blue",
        color: "white",
      }}
    >
      <h1>About ({location.pathname})</h1>
    </div>
  );
};
