// apps/vue-app/src/views/About.vue
<script>
import { defineComponent, defineAsyncComponent, ref } from "vue";

export default defineComponent({
  components: {
    AboutComponent: defineAsyncComponent(() =>
      window.serviceLocator.resolve("about-vue")
    ),
  },

  setup() {
    const title = ref("About");
    const toggleTitle = () => {
      title.value = title.value === "About" ? "About Vue" : "About";
    };

    return {
      title,
      toggleTitle,
    };
  },
});
</script>

<template>
  <button @click="toggleTitle">Toggle Title</button>
  <AboutComponent :title="title" />
</template>

// apps/react-app/src/views/About.js
import React, { lazy, Suspense } from "react";

const AboutLazy = lazy(() => window.serviceLocator.resolve("about-react"));

export default () => {
  const [title, setTitle] = React.useState("About React");

  const toggleTitle = () => {
    setTitle(() => (title === "About" ? "About React" : "About"));
  };

  return (
    <Suspense fallback={<div>loading...</div>}>
      <>
        <button onClick={() => toggleTitle()}>toggle title</button>
        <AboutLazy title={title} />
      </>
    </Suspense>
  );
};
