// apps/about-react/src/App.js
import React, { useEffect } from "react";

const About = () => {
  useEffect(() => {
    let app = null;
    const containerSelectors = "#about";
    (async () => {
      app = await window.serviceLocator.resolve("about-uni");

      app.mount({
        containerSelectors,
      });
    })();

    return () => {
      app?.unmount({
        containerSelectors,
      });
      app = null;
    };
  }, []);

  return <div id="about"></div>;
};

export default About;

// apps/about-vue/src/App.vue
<script setup>
import { ref, onMounted, onBeforeUnmount } from "vue";

const appPromise = window.serviceLocator.resolve("about-uni");
const about = ref();
let isMounting = false;
onMounted(async () => {
  isMounting = true;
  const app = await appPromise;

  if (isMounting) {
    app.mount({
      containerSelectors: about.value,
    });
  }
});
onBeforeUnmount(() => {
  isMounting = false;
});
</script>

<template>
  <div ref="about"></div>
</template>
